#!/bin/bash
# A/B on Ethan's established schedule_20 (generated by schedule_generation/
# run_schedule_generation.sh: 2400 tasks, balanced 1242 in / 1158 out, 1200
# ticks). Replays the SAME schedule under plain M2M and M2M+crM2M. Doubles as
# the replay deadlock-check for the standalone generator.
set -uo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
PY="$repo_root/.venv/bin/python"
RAW="$repo_root/data/raw_data"; LOG="$repo_root/data/logs"
cd "$repo_root"; mkdir -p "$RAW" "$LOG"
MAP="$repo_root/data/maps/study_small_restricted"
SCHED="$repo_root/data/schedules/schedule_20.txt"
INV="$repo_root/data/initial_inventories/schedule_20_init_inventory.txt"
BASE_JSON="$RAW/1200_precomputed_schedule_30.0_fast_greedy_py_lns_pbs_study_small_restricted_30_120_1.0_0.0_0.0_none_none_900.json"

common=(
  --seed 900 --num-robots 30 --time-horizon 1200 --max-tasks 120
  --initial-task-assign-strategy fast_greedy --improvement-task-assign-strategy py_lns
  --path-planning-strategy pbs
  --initial-inventory 30.0 --frequency 0.25 --inbound-outbound-ratio 1.0 --num-skus 30
  --weight-init-method uniform --map "$MAP" --cost-calculation-method shortest_path
  --removal-operator shaw --repair-operator greedy --acceptance-function simulated_annealing
  --T-0 1.0 --alpha 0.99 --deadline-generation-method normal --deadline-offset 180
  --intermediate-data-interval 4000
  --base-cost-weight 1.0 --deadline-weight 0.0 --sku-distribution-weight 0.0
  --agent-unallocated-penalty 5.0
  --solution-repair-detection-function none --solution-repair-function none
  --task-gen-strategy feedback_control
  --use-precomputed-schedule --schedule-file "$SCHED" --initial-inventory-file "$INV"
)

echo "=== RUN 1/2: regular M2M on schedule_20 ==="
"$PY" -u GT_grid_world/GT_grid_world.py "${common[@]}" > "$LOG/s20_m2m.log" 2>&1
mv -f "$BASE_JSON" "$RAW/cmp_m2m_schedule20_30bot_1200t_seed900.json"
echo "RUN 1 done"

echo "=== RUN 2/2: M2M + crM2M on schedule_20 ==="
"$PY" -u GT_grid_world/GT_grid_world.py "${common[@]}" --enable-rearrangement > "$LOG/s20_crm2m.log" 2>&1
mv -f "$BASE_JSON" "$RAW/cmp_crm2m_schedule20_30bot_1200t_seed900.json"
echo "RUN 2 done"

echo "=== FIGURES: regenerate the six canonical M2M vs crM2M figures ==="
mkdir -p "$repo_root/data/figures"
(cd "$repo_root/GT_grid_world/scripts" && "$PY" plot_crm2m_compare.py \
  "$RAW/cmp_m2m_schedule20_30bot_1200t_seed900.json" \
  "$RAW/cmp_crm2m_schedule20_30bot_1200t_seed900.json" \
  "$repo_root/data/figures") > "$LOG/s20_figures.log" 2>&1
echo "FIGURES done"
echo "SCHEDULE20_AB_COMPLETE"
